"""version str -> int (step 1 delete)

Revision ID: 21cb6f015111
Revises: fb525c3ebafb
Create Date: 2022-10-12 23:19:52.480356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21cb6f015111'
down_revision = 'fb525c3ebafb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirement', 'version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirement', sa.Column('version', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
