"""delete indexes

Revision ID: 5400424258ff
Revises: a1eb94866e33
Create Date: 2022-09-28 17:26:31.034279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5400424258ff'
down_revision = 'a1eb94866e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_role', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.create_index('ix_user_role', 'user', ['role'], unique=False)
    # ### end Alembic commands ###
