"""fields change

Revision ID: 57fff5de7b29
Revises: f4ccaadc718c
Create Date: 2022-10-06 22:57:11.708715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57fff5de7b29'
down_revision = 'f4ccaadc718c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirement', sa.Column('requirement_id', sa.Integer(), nullable=True))
    op.drop_constraint('requirement_parent_id_fkey', 'requirement', type_='foreignkey')
    op.create_foreign_key(None, 'requirement', 'requirement_tree', ['requirement_id'], ['id'])
    op.drop_column('requirement', 'parent_id')
    op.drop_column('requirement_tree', 'requirement_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirement_tree', sa.Column('requirement_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('requirement', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'requirement', type_='foreignkey')
    op.create_foreign_key('requirement_parent_id_fkey', 'requirement', 'requirement_tree', ['parent_id'], ['id'])
    op.drop_column('requirement', 'requirement_id')
    # ### end Alembic commands ###
