"""add FK priority

Revision ID: 6900af420936
Revises: bf583bd6ac5a
Create Date: 2022-10-05 14:09:08.923980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6900af420936'
down_revision = 'bf583bd6ac5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('user')
    op.add_column('requirement', sa.Column('priorty', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'requirement', 'requirement_priority', ['priorty'], ['id'])
    op.drop_column('requirement', 'priorty_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirement', sa.Column('priorty_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'requirement', type_='foreignkey')
    op.drop_column('requirement', 'priorty')
    # op.create_table('user',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    # sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    # sa.Column('role', postgresql.ENUM('ADMIN', 'USER', name='roles'), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name='user_pkey'),
    # sa.UniqueConstraint('username', name='user_username_key')
    # )
    # ### end Alembic commands ###
