"""create release boolean

Revision ID: 7097e228f103
Revises: c33eb337a31a
Create Date: 2022-11-02 15:23:07.032389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7097e228f103'
down_revision = 'c33eb337a31a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirement', sa.Column('release', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirement', 'release')
    # ### end Alembic commands ###
