"""add created_date in ruquirementtree

Revision ID: 9b6cd2d5545c
Revises: 57fff5de7b29
Create Date: 2022-10-10 20:50:48.690320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b6cd2d5545c'
down_revision = '57fff5de7b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirement_tree', sa.Column('created_date', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc0')"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirement_tree', 'created_date')
    # ### end Alembic commands ###
