"""accept_rool table

Revision ID: aeb2a5c3186c
Revises: b578ce47690b
Create Date: 2022-10-22 13:03:48.922238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from rms.user.enums import Roles


# revision identifiers, used by Alembic.
revision = 'aeb2a5c3186c'
down_revision = 'b578ce47690b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accept_requirement_rool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_type', sa.Integer(), nullable=False),
    sa.Column('accept_role', postgresql.ENUM(Roles, name='roles', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['requirement_type'], ['requirement_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_type', 'accept_role')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accept_requirement_rool')
    # ### end Alembic commands ###
