"""fix naming

Revision ID: b578ce47690b
Revises: 94738ba756e8
Create Date: 2022-10-18 18:43:14.996171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b578ce47690b'
down_revision = '94738ba756e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirement', sa.Column('requirement_id', sa.Integer(), nullable=True))
    op.drop_constraint('requirement_requirement_node_id_fkey', 'requirement', type_='foreignkey')
    op.create_foreign_key(None, 'requirement', 'requirement_tree', ['requirement_id'], ['id'])
    op.drop_column('requirement', 'requirement_node_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirement', sa.Column('requirement_node_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'requirement', type_='foreignkey')
    op.create_foreign_key('requirement_requirement_node_id_fkey', 'requirement', 'requirement_tree', ['requirement_node_id'], ['id'])
    op.drop_column('requirement', 'requirement_id')
    # ### end Alembic commands ###
