"""fix naming

Revision ID: b578ce47690b
Revises: 94738ba756e8
Create Date: 2022-10-18 18:43:14.996171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b578ce47690b'
down_revision = '94738ba756e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requirement', 'requirement_node_id',  new_column_name='requirement_id', existing_type=sa.Integer)
    op.drop_constraint('requirement_requirement_node_id_fkey', 'requirement', type_='foreignkey')
    op.create_foreign_key(None, 'requirement', 'requirement_tree', ['requirement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requirement', 'requirement_id', new_column_name='requirement_node_id', existing_type=sa.Integer)
    op.drop_constraint('requirement_requirement_id_fkey', 'requirement', type_='foreignkey')
    op.create_foreign_key('requirement_requirement_node_id_fkey', 'requirement', 'requirement_tree', ['requirement_node_id'], ['id'])
    # ### end Alembic commands ###
