"""add tables requirement_(priority, type)

Revision ID: bf583bd6ac5a
Revises: 9cf766bc533f
Create Date: 2022-10-05 00:34:15.848088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf583bd6ac5a'
down_revision = '9cf766bc533f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirement_priority',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirement_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requirement_types')
    op.drop_table('requirement_priority')
    # ### end Alembic commands ###
