"""add create date in Requirement_tree

Revision ID: d511b3bb974e
Revises: 57fff5de7b29
Create Date: 2022-10-07 17:40:04.890231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd511b3bb974e'
down_revision = '57fff5de7b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirement_tree', sa.Column('created_date', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc0')"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirement_tree', 'created_date')
    # ### end Alembic commands ###
