"""version str -> int (step 2 create)

Revision ID: e73c8ac63d20
Revises: 21cb6f015111
Create Date: 2022-10-12 23:21:06.041798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73c8ac63d20'
down_revision = '21cb6f015111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirement', sa.Column('version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirement', 'version')
    # ### end Alembic commands ###
