"""add relationships to requirements

Revision ID: f4ccaadc718c
Revises: 6900af420936
Create Date: 2022-10-05 14:28:42.205152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4ccaadc718c'
down_revision = '6900af420936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirement', sa.Column('status_id', sa.Integer(), nullable=True))
    op.add_column('requirement', sa.Column('priority_id', sa.Integer(), nullable=True))
    op.drop_constraint('requirement_priorty_fkey', 'requirement', type_='foreignkey')
    op.create_foreign_key(None, 'requirement', 'requirement_statuses', ['status_id'], ['id'])
    op.create_foreign_key(None, 'requirement', 'requirement_types', ['type_id'], ['id'])
    op.create_foreign_key(None, 'requirement', 'requirement_priority', ['priority_id'], ['id'])
    op.drop_column('requirement', 'priorty')
    op.drop_column('requirement', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirement', sa.Column('status', postgresql.ENUM('new', 'on_review', 'active', 'old', 'changed', name='requirement_status'), autoincrement=False, nullable=True))
    op.add_column('requirement', sa.Column('priorty', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'requirement', type_='foreignkey')
    op.drop_constraint(None, 'requirement', type_='foreignkey')
    op.drop_constraint(None, 'requirement', type_='foreignkey')
    op.create_foreign_key('requirement_priorty_fkey', 'requirement', 'requirement_priority', ['priorty'], ['id'])
    op.drop_column('requirement', 'priority_id')
    op.drop_column('requirement', 'status_id')
    # ### end Alembic commands ###
